### meta-data variables
title: "Mr Zech's RPGs"
description: "Mr Zech's RPG musings and projects"
email: "mrzech.com@gmail.com"
url: "https://zechlau14.github.io"
# avatar: (URL)

### theme and visuals
remote_theme: barryclark/jekyll-now
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

### Functionalities
# disqus: [discus id] for comments
# google_analytics: [Google Analytics tracking ID] 
